version: '3'
services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.7
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entryPoints.http.address=:80"
    ports:
      - "127.0.0.1:8100:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/digital-blueprint/dispatch-app:latest
    restart: unless-stopped
    volumes:
      - ./web/.htaccess:/usr/local/apache2/htdocs/.htaccess:ro
      - ./web/app.webmanifest:/usr/local/apache2/htdocs/app/app.webmanifest:ro
      - ./web/index.html:/usr/local/apache2/htdocs/index.html:ro
      - ./web/topic.metadata.json:/usr/local/apache2/htdocs/app/dbp-dispatch.topic.metadata.json:ro
    labels:
      # http://dbp-web.localhost:8100
      - "traefik.http.routers.web-router.rule=Host(`dbp-web.localhost`, `localhost`, `127.0.0.1`)"
      - "traefik.http.routers.web-router.entrypoints=http"
    depends_on:
      - keycloak

  postgres:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@example.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    labels:
#      # http://pgadmin.localhost:8100
#      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
#      - "traefik.http.routers.pgadmin.entrypoints=http"
#      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
#    volumes:
#      - pgadmin:/var/lib/pgadmin

  keycloak:
#    image: quay.io/keycloak/keycloak:21.0
    image: quay.io/keycloak/keycloak:20.0.3
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_FRONTEND_URL: http://keycloak.localhost:8100
    command:
      - start-dev
#      - --hostname=keycloak.localhost
      - --import-realm
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    labels:
      # http://keycloak.localhost:8100
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=http"
    depends_on:
      - postgres


  # TODO: Add services for the API, ...

volumes:
  postgres_data:
#  pgadmin:
