version: '3'
services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.7
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entryPoints.http.address=:80"
    ports:
      - "127.0.0.1:8100:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: ghcr.io/digital-blueprint/dispatch-app:latest
    restart: unless-stopped
#    ports:
#      # http://localhost:8081
#      - "8081:80"
    volumes:
      - ./web/.htaccess:/usr/local/apache2/htdocs/.htaccess:ro
      - ./web/app.webmanifest:/usr/local/apache2/htdocs/app.webmanifest:ro
      - ./web/index.html:/usr/local/apache2/htdocs/index.html:ro
      - ./web/topic.metadata.json:/usr/local/apache2/htdocs/topic.metadata.json:ro
    labels:
      # http://dispatch-example.localhost:8100
      - "traefik.http.routers.web-router.rule=Host(`dispatch-example.localhost`, `localhost`, `127.0.0.1`)"
      - "traefik.http.routers.web-router.entrypoints=http"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
#    image: jboss/keycloak:latest
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KEYCLOAK_FRONTEND_URL=http://keycloak.localhost:8100
    command:
      - start-dev
      - --hostname=keycloak.localhost
      - --import-realm
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    labels:
      # http://keycloak.localhost:8100
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=http"


  # TODO: Add services for the API, Keycloak, ...
