version: "3"
services:
  web:
    image: dispatch-app
    build: .
    container_name: dispatch-app
    restart: unless-stopped
    ports:
      # http://localhost:8081
      - "8081:80"
#  web:
#    image: ghcr.io/digital-blueprint/dispatch-app:latest
#    container_name: dispatch-app
#    restart: always
#    ports:
#      - "8081:80"
