version: '3'

services:
  nextcloud:
    build: ./nextcloud
    ports:
      - 8081:80
    environment:
      - WEBPASSWORD_ORIGINS=http://127.0.0.1:8001,http://localhost:8001,http://localhost:8082,http://bs-local.com:8001
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=mydb
      - NEXTCLOUD_TRUSTED_DOMAINS=bs-local.com localhost 127.0.0.1
    volumes:
      - nextcloud:/var/www/html
      - ./webapppassword.config.php:/var/www/html/config/webapppassword.config.php
  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  nextcloud:
  elasticsearch:
